INSERT INTO Challenges (title, description, category, difficulty, CO2_reduction_kg) VALUES
('Turn Off Lights', 'Turn off lights when leaving a room.', 'Energy Saving', 'Easy', 0.1),
('Bring Your Own Bag', 'Use a reusable bag instead of a plastic one when shopping.', 'Waste Reduction', 'Easy', 0.04),
('Walk or Cycle', 'Choose walking or cycling for a short trip instead of using a car.', 'Transportation', 'Easy', 0.5),
('Unplug Devices', 'Unplug electronics when they are not in use.', 'Energy Saving', 'Easy', 0.2),
('Use a Refillable Water Bottle', 'Ditch single-use plastic bottles and use a refillable water bottle.', 'Waste Reduction', 'Easy', 0.1),
('Shorter Showers', 'Take a shower that lasts no more than 5 minutes.', 'Water Conservation', 'Easy', 0.3),
('Use Both Sides of Paper', 'Write or print on both sides of the paper.', 'Waste Reduction', 'Easy', 0.02),
('Eat Local', 'Choose one meal made with locally-sourced ingredients.', 'Diet', 'Easy', 0.3),
('Say No to Straws', 'Avoid using single-use plastic straws for a day.', 'Waste Reduction', 'Easy', 0.01),
('Turn Down the Heat', 'Lower your thermostat by 1 degree to save energy.', 'Energy Saving', 'Easy', 0.5),
('Wash in Cold Water', 'Do your laundry with cold water to save energy.', 'Energy Saving', 'Easy', 0.3),
('Recycle Properly', 'Ensure all recyclable items are clean and sorted correctly.', 'Waste Reduction', 'Easy', 0.1),
('Replace Lightbulbs', 'Replace one incandescent bulb with an LED.', 'Energy Saving', 'Easy', 0.5),
('Use Public Transportation', 'Take a bus, train, or shared vehicle instead of driving.', 'Transportation', 'Easy', 0.2),
('Bring Your Own Cup', 'Bring a reusable cup for your coffee or tea.', 'Waste Reduction', 'Easy', 0.02),
('Air Dry Clothes', 'Skip the dryer and air-dry your clothes today.', 'Energy Saving', 'Easy', 0.3),
('Use a Bar of Soap', 'Switch to a bar of soap to reduce plastic waste.', 'Waste Reduction', 'Easy', 0.01),
('Share a Ride', 'Carpool with friends or coworkers for a trip.', 'Transportation', 'Easy', 0.4),
('Go Paperless', 'Opt for digital receipts and statements.', 'Waste Reduction', 'Easy', 0.05),
('Skip the Elevator', 'Use the stairs instead of the elevator.', 'Energy Saving', 'Easy', 0.02),
('Reuse Packaging', 'Reuse a box or package for storage or another purpose.', 'Waste Reduction', 'Easy', 0.03),
('Avoid Prepackaged Foods', 'Choose fresh or bulk foods to reduce packaging waste.', 'Diet', 'Easy', 0.3),
('Donate Old Items', 'Give away items you no longer use instead of throwing them out.', 'Waste Reduction', 'Easy', 0.2),
('Fix Something', 'Repair a broken item instead of discarding it.', 'Consumption', 'Easy', 0.2),
('Close Doors and Windows', 'Keep doors and windows closed while the AC or heat is on.', 'Energy Saving', 'Easy', 0.2),
('Meal Plan', 'Plan your meals to reduce food waste.', 'Diet', 'Easy', 0.1),
('Use Cloth Towels', 'Replace paper towels with reusable cloth ones.', 'Waste Reduction', 'Easy', 0.05),
('Download Instead of Stream', 'Download media instead of streaming to save energy.', 'Energy Saving', 'Easy', 0.3),
('Conserve Water', 'Turn off the tap while brushing your teeth.', 'Water Conservation', 'Easy', 0.02),
('Recycle Electronics', 'Drop off old electronics at a recycling facility.', 'Waste Reduction', 'Easy', 0.15),
('Take Public Transportation', 'Use public transit instead of driving your car today.', 'Transportation', 'Medium', 1.0),
('Go Vegetarian for a Day', 'Reduce your carbon footprint by skipping meat for one day.', 'Diet', 'Medium', 1.5),
('Compost Your Food Waste', 'Start a compost bin for your organic waste instead of throwing it away.', 'Waste Reduction', 'Medium', 0.4),
('Batch Cook Meals', 'Prepare meals in bulk to save energy and reduce waste.', 'Diet', 'Medium', 0.5),
('Use Natural Light', 'Keep lights off during the day and rely on sunlight.', 'Energy Saving', 'Medium', 0.6),
('Buy in Bulk', 'Purchase items in bulk to reduce packaging waste.', 'Consumption', 'Medium', 0.3),
('Switch to Renewable Energy', 'Sign up for renewable energy plans if available.', 'Energy Saving', 'Medium', 1.5),
('Grow Your Own Herbs', 'Start a small herb garden at home.', 'Environment', 'Medium', 0.1),
('Line Dry Laundry', 'Skip the dryer entirely and hang-dry all your clothes today.', 'Energy Saving', 'Medium', 0.3),
('Reduce Food Miles', 'Buy food that was grown or made within 100 miles of your home.', 'Diet', 'Medium', 0.4),
('Install Faucet Aerators', 'Install aerators on your faucets to reduce water use.', 'Water Conservation', 'Medium', 0.05),
('Switch to E-Books', 'Read a book digitally instead of buying a paper copy.', 'Consumption', 'Medium', 0.1),
('Bike to Work or School', 'Replace a car trip with a bike ride for your commute.', 'Transportation', 'Medium', 0.5),
('Eliminate Phantom Energy', 'Use a power strip to turn off all devices at night.', 'Energy Saving', 'Medium', 0.2),
('Cook Efficiently', 'Cook multiple dishes at once to maximize energy use.', 'Energy Saving', 'Medium', 0.4),
('Ditch Disposable Razors', 'Use a reusable razor instead of disposables.', 'Waste Reduction', 'Medium', 0.07),
('Avoid Air Conditioning', 'Rely on fans or natural ventilation instead of air conditioning.', 'Energy Saving', 'Medium', 0.6),
('Avoid Fast Food', 'Skip fast food today to reduce waste and energy use.', 'Diet', 'Medium', 0.5),
('Switch to Reusable Napkins', 'Use cloth napkins instead of paper ones.', 'Waste Reduction', 'Medium', 0.02),
('Host a Clothing Swap', 'Organize a clothing swap with friends to reuse items.', 'Consumption', 'Medium', 0.2),
('Pick Up Litter', 'Spend 15 minutes picking up litter in your neighborhood.', 'Environment', 'Medium', 0.05),
('Install a Rain Barrel', 'Collect rainwater to use for watering plants.', 'Water Conservation', 'Medium', 0.1),
('Eliminate Single-Use Plastics', 'Go the entire day without using any single-use plastics.', 'Waste Reduction', 'Medium', 0.3),
('Reduce Water Heating Temperature', 'Lower your water heater\'s temperature to save energy.', 'Energy Saving', 'Medium', 0.4),
('Donate Unused Electronics', 'Find a charity or recycling program for old gadgets.', 'Waste Reduction', 'Medium', 0.1),
('Support a Local Farmers\' Market', 'Buy fresh, local produce instead of store-bought items.', 'Diet', 'Medium', 0.3),
('Plan Errands Efficiently', 'Group errands to minimize driving distances.', 'Transportation', 'Medium', 0.4),
('Save Rainwater', 'Collect rainwater for household use or plants.', 'Water Conservation', 'Medium', 0.1),
('Invest in Quality Items', 'Buy durable, high-quality items that last longer.', 'Consumption', 'Medium', 0.2),
('Advocate for Green Policies', 'Write to your local representative about environmental issues.', 'Community', 'Medium', 0.05),
('Refuse Junk Mail', 'Unsubscribe from junk mail to reduce paper waste.', 'Waste Reduction', 'Medium', 0.03),
('Participate in a Cleanup Event', 'Join a local cleanup event to improve your community.', 'Environment', 'Medium', 0.1),
('Switch to Rechargeable Batteries', 'Use rechargeable batteries instead of disposable ones.', 'Waste Reduction', 'Medium', 0.2),
('Buy Energy-Efficient Appliances', 'Choose energy-efficient options for your next appliance purchase.', 'Energy Saving', 'Medium', 1.0),
('Switch to Sustainable Clothing', 'Purchase clothing made from sustainable materials.', 'Consumption', 'Medium', 0.2),
('Install Low-Flow Showerheads', 'Reduce water usage by installing low-flow showerheads.', 'Water Conservation', 'Medium', 0.3),
('Switch to a Paperless Office', 'Make your office work more digital and reduce paper waste.', 'Waste Reduction', 'Medium', 0.5),
('Reduce Meat Consumption', 'Try cutting back on meat consumption to reduce your environmental impact.', 'Diet', 'Medium', 0.7),
('Opt for a Green Energy Plan', 'Choose a green energy plan for your home.', 'Energy Saving', 'Medium', 1.0),
('Switch to Cloth Diapers', 'Use cloth diapers instead of disposable ones.', 'Waste Reduction', 'Medium', 0.4),
('Host a Zero-Waste Party', 'Organize a zero-waste event with reusable items and no disposable plastics.', 'Waste Reduction', 'Medium', 0.2),
('Support Electric Vehicle Adoption', 'Encourage the use of electric vehicles in your community.', 'Transportation', 'Medium', 0.8),
('Join a Green Organization', 'Support environmental organizations and participate in their programs.', 'Community', 'Medium', 0.1),
('Grow Your Own Vegetables', 'Start a garden to grow your own vegetables.', 'Diet', 'Medium', 0.5),
('Go Solar', 'Install solar panels for your home to use renewable energy.', 'Energy Saving', 'High', 5.0),
('Purchase Carbon Offsets', 'Invest in carbon offset programs to neutralize your carbon footprint.', 'Environment', 'High', 2.0),
('Install Solar Water Heating', 'Install a solar water heating system for your home.', 'Energy Saving', 'High', 1.5),
('Reduce Long-Distance Travel', 'Avoid long-distance air travel, and choose local trips instead.', 'Transportation', 'High', 2.0),
('Buy Electric or Hybrid Car', 'Choose an electric or hybrid car instead of a conventional one.', 'Transportation', 'High', 3.0),
('Support Reforestation', 'Contribute to or volunteer for reforestation programs.', 'Environment', 'High', 1.5),
('Buy Sustainable Furniture', 'Opt for furniture made from sustainable materials.', 'Consumption', 'High', 0.5),
('Switch to a Low-Carbon Diet', 'Make changes to your diet by reducing animal-based products.', 'Diet', 'High', 1.0),
('Install a Green Roof', 'Transform your roof into a green space to increase insulation and reduce carbon impact.', 'Energy Saving', 'High', 1.2),
('Build an Eco-Friendly House', 'Construct a home using sustainable building materials.', 'Consumption', 'High', 5.0),
('Plant a Forest', 'Participate in or fund a project to plant a significant number of trees.', 'Environment', 'Hard', 9.0),
('Go Off-Grid for Energy', 'Transition your home to operate off-grid using renewable energy sources.', 'Energy Saving', 'Hard', 3.0),
('Quit Fast Fashion Entirely', 'Commit to buying only second-hand or sustainable clothing from now on.', 'Consumption', 'Hard', 1.5),
('Host a Zero-Waste Event', 'Organize an event where no waste is generated, using only reusable or compostable items.', 'Waste Reduction', 'Hard', 0.5),
('Reduce Utility Use by 30%', 'Cut your electricity, water, and heating usage by 30% over the next month.', 'Energy Saving', 'Hard', 4.0),
('Volunteer for Environmental Advocacy', 'Dedicate 10+ hours to supporting environmental advocacy or restoration projects.', 'Community', 'Hard', 0.2),
('Commit to Minimalism', 'Downsize your possessions and only keep items you truly need.', 'Consumption', 'Hard', 0.4),
('Switch to Ethical Banking', 'Move your savings or investments to a bank that supports sustainable initiatives.', 'Community', 'Hard', 0.05),
('Install a Greywater System', 'Set up a system to reuse wastewater from sinks and showers for irrigation.', 'Water Conservation', 'Hard', 0.6),
('Live a Plastic-Free Month', 'Avoid all plastic products and packaging for an entire month.', 'Waste Reduction', 'Hard', 1.5),
('Start a Community Garden', 'Establish and maintain a community garden for shared use.', 'Environment', 'Hard', 0.5),
('Reuse Gift Wrapping', 'Save wrapping paper or gift bags to reuse for future gifts.', 'Waste Reduction', 'Easy', 0.02),
('Turn Off Your Computer', 'Shut down your computer completely at the end of the day instead of leaving it in sleep mode.', 'Energy Saving', 'Easy', 0.1),
('Plant a Flower', 'Plant a flower or a small plant to support local pollinators like bees and butterflies.', 'Environment', 'Easy', 0.05),
('Opt for Refillable Pens', 'Switch to using pens that can be refilled with ink, reducing plastic waste.', 'Waste Reduction', 'Easy', 0.01),
('DIY Cleaning Products', 'Create your own cleaning products using common household ingredients like vinegar and baking soda.', 'Waste Reduction', 'Easy', 0.1),
('Carry Reusable Utensils', 'Bring your own reusable utensils (spork, fork, knife) to avoid disposable ones when eating on the go.', 'Waste Reduction', 'Easy', 0.03),
('Skip the Dryer Sheets', 'Use wool dryer balls instead of disposable dryer sheets to reduce waste and chemicals in laundry.', 'Waste Reduction', 'Easy', 0.02),
('Drink Tap Water', 'Opt for tap water instead of bottled water to reduce plastic waste and save money.', 'Waste Reduction', 'Easy', 0.15),
('Borrow a Book', 'Instead of buying new books, borrow them from a library or a friend to reduce consumption and waste.', 'Consumption', 'Easy', 0.05),
('Pick Up Trash', 'Pick up at least 5 pieces of trash on your walk to help keep your community clean.', 'Environment', 'Easy', 0.01),
('Use a Digital Calendar', 'Switch from paper planners to a digital calendar to reduce paper waste.', 'Waste Reduction', 'Easy', 0.03),
('Buy Loose Produce', 'Purchase loose fruits and vegetables instead of pre-packaged ones to reduce plastic waste.', 'Consumption', 'Easy', 0.1),
('Take a No-Plastic Lunch', 'Pack your lunch using reusable containers, avoiding plastic wrappers and bags.', 'Waste Reduction', 'Easy', 0.2),
('Use Energy-Efficient Settings', 'Switch your appliances and electronics to energy-efficient modes to conserve energy.', 'Energy Saving', 'Easy', 0.3),
('Avoid Pre-Rinse', 'Do not pre-rinse dishes before placing them in the dishwasher to save water and energy.', 'Water Conservation', 'Easy', 0.15),
('Freeze Leftovers', 'Freeze leftover meals to avoid food waste and make use of leftovers in the future.', 'Waste Reduction', 'Easy', 0.2),
('Take a Nature Walk', 'Spend time outdoors, take a walk in nature, and appreciate the beauty of your surroundings.', 'Environment', 'Easy', 0.01),
('Use Matches Instead of Lighters', 'Switch to using matches instead of disposable lighters, as they are more eco-friendly.', 'Waste Reduction', 'Easy', 0.02),
('Repair Clothes', 'Instead of discarding old or damaged clothing, repair it to extend its life and reduce waste.', 'Waste Reduction', 'Easy', 0.1),
('Share Your Knowledge', 'Teach someone else about a simple eco-friendly habit you practice to encourage sustainability.', 'Community', 'Easy', 0.05);

