INSERT INTO Challenges (title, description, category, difficulty, CO2_reduction_kg, coins, impact) VALUES
('Turn Off Lights', 'Turn off lights when leaving a room.', 'Energy Saving', 'Easy', 0.1, 1, 'Equivalent to the CO2 absorbed by a small tree in a day.'),
('Bring Your Own Bag', 'Use a reusable bag instead of a plastic one when shopping.', 'Waste Reduction', 'Easy', 0.04, 1, 'Equivalent to the CO2 absorbed by 2 square meters of forest in a day.'),
('Walk or Cycle', 'Choose walking or cycling for a short trip instead of using a car.', 'Transportation', 'Easy', 0.5, 1, 'Equivalent to the CO2 absorbed by a medium-sized tree in a day.'),
('Unplug Devices', 'Unplug electronics when they are not in use.', 'Energy Saving', 'Easy', 0.2, 1, 'Equivalent to the energy saved by a 10-watt LED light bulb running for 20 hours.'),
('Use a Refillable Water Bottle', 'Ditch single-use plastic bottles and use a refillable water bottle.', 'Waste Reduction', 'Easy', 0.1, 1, 'Equivalent to the CO2 emitted by producing 2 single-use plastic bottles.'),
('Shorter Showers', 'Take a shower that lasts no more than 5 minutes.', 'Water Conservation', 'Easy', 0.3, 1, 'Equivalent to the CO2 emitted by boiling 1 liter of water.'),
('Use Both Sides of Paper', 'Write or print on both sides of the paper.', 'Waste Reduction', 'Easy', 0.02, 1, 'Equivalent to the CO2 absorbed by a small plant for a week.'),
('Eat Local', 'Choose one meal made with locally-sourced ingredients.', 'Diet', 'Easy', 0.3, 1, 'Equivalent to the CO2 emissions of 3 kilometers of car travel.'),
('Say No to Straws', 'Avoid using single-use plastic straws for a day.', 'Waste Reduction', 'Easy', 0.01, 1, 'Equivalent to the CO2 absorbed by a small shrub over a month.'),
('Turn Down the Heat', 'Lower your thermostat by 1 degree to save energy.', 'Energy Saving', 'Easy', 0.5, 1, 'Equivalent to the CO2 emitted by driving 2 kilometers in a car.'),
('Wash in Cold Water', 'Do your laundry with cold water to save energy.', 'Energy Saving', 'Easy', 0.3, 1, 'Equivalent to the CO2 saved by turning off a 100-watt light bulb for 4 hours.'),
('Recycle Properly', 'Ensure all recyclable items are clean and sorted correctly.', 'Waste Reduction', 'Easy', 0.1, 1, 'Equivalent to saving 10 plastic bottles from ending up in a landfill.'),
('Replace Lightbulbs', 'Replace one incandescent bulb with an LED.', 'Energy Saving', 'Easy', 0.5, 1, 'Equivalent to the CO2 absorbed by a large tree in a week.'),
('Use Public Transportation', 'Take a bus, train, or shared vehicle instead of driving.', 'Transportation', 'Easy', 0.2, 1, 'Equivalent to the CO2 absorbed by 1 square meter of forest in a year.'),
('Bring Your Own Cup', 'Bring a reusable cup for your coffee or tea.', 'Waste Reduction', 'Easy', 0.02, 1, 'Equivalent to reducing plastic waste from 2 disposable cups.'),
('Air Dry Clothes', 'Skip the dryer and air-dry your clothes today.', 'Energy Saving', 'Easy', 0.3, 1, 'Equivalent to the energy saved by turning off a 500-watt dryer for an hour.'),
('Use a Bar of Soap', 'Switch to a bar of soap to reduce plastic waste.', 'Waste Reduction', 'Easy', 0.01, 1, 'Equivalent to reducing plastic waste from 10 liquid soap bottles.'),
('Share a Ride', 'Carpool with friends or coworkers for a trip.', 'Transportation', 'Easy', 0.4, 1, 'Equivalent to the CO2 absorbed by 1 tree in 5 days.'),
('Go Paperless', 'Opt for digital receipts and statements.', 'Waste Reduction', 'Easy', 0.05, 1, 'Equivalent to saving 100 sheets of paper.'),
('Skip the Elevator', 'Use the stairs instead of the elevator.', 'Energy Saving', 'Easy', 0.02, 1, 'Equivalent to the CO2 saved by not running the elevator for 5 minutes.'),
('Reuse Packaging', 'Reuse a box or package for storage or another purpose.', 'Waste Reduction', 'Easy', 0.03, 1, 'Equivalent to the CO2 produced by manufacturing 1 plastic container.'),
('Avoid Prepackaged Foods', 'Choose fresh or bulk foods to reduce packaging waste.', 'Diet', 'Easy', 0.3, 1, 'Equivalent to reducing plastic waste from 5 prepackaged meals.'),
('Donate Old Items', 'Give away items you no longer use instead of throwing them out.', 'Waste Reduction', 'Easy', 0.2, 1, 'Equivalent to reducing the CO2 from sending items to a landfill.'),
('Fix Something', 'Repair a broken item instead of discarding it.', 'Consumption', 'Easy', 0.2, 1, 'Equivalent to preventing the CO2 from manufacturing a replacement item.'),
('Close Doors and Windows', 'Close doors and windows when using heat or air conditioning.', 'Energy Saving', 'Easy', 0.4, 1, 'Equivalent to saving energy from heating or cooling a room for 2 hours.'),
('Use a Smart Thermostat', 'Install a smart thermostat to optimize energy usage.', 'Energy Saving', 'Moderate', 0.5, 1, 'Equivalent to reducing the CO2 from running a heater for 3 hours.'),
('Reduce Water Heating Time', 'Reduce the time you run the hot water faucet.', 'Water Conservation', 'Easy', 0.1, 1, 'Equivalent to cutting down on water heating for 20 minutes.'),
('Use Cloth Napkins', 'Switch to cloth napkins instead of paper ones.', 'Waste Reduction', 'Easy', 0.02, 1, 'Equivalent to saving 100 paper napkins from being produced.'),
('Switch to LED Bulbs', 'Replace incandescent bulbs with energy-efficient LED bulbs.', 'Energy Saving', 'Easy', 0.5, 1, 'Equivalent to reducing the CO2 from 10,000 hours of incandescent bulb use.'),
('Use Less Paper Towels', 'Switch to reusable towels instead of using paper ones.', 'Waste Reduction', 'Easy', 0.02, 1, 'Equivalent to saving 100 paper towels from production.'),
('Compost Food Waste', 'Compost organic waste instead of sending it to the landfill.', 'Waste Reduction', 'Easy', 0.5, 1, 'Equivalent to preventing methane emissions from food waste in a landfill.'),
('Fix Leaks', 'Fix any leaky faucets or pipes to reduce water waste.', 'Water Conservation', 'Easy', 0.1, 1, 'Equivalent to reducing water waste by 10 liters per day.'),
('Use a Dryer Ball', 'Use a dryer ball to reduce drying time and save energy.', 'Energy Saving', 'Easy', 0.1, 1, 'Equivalent to the energy saved by running a dryer for 10 minutes.'),
('Switch to Solar', 'Install solar panels for a renewable energy source.', 'Energy Saving', 'Hard', 10, 1, 'Equivalent to eliminating the CO2 emissions from 30,000 kilometers of car travel.'),
('Skip the Meat', 'Go one day a week without eating meat.', 'Diet', 'Moderate', 2, 1, 'Equivalent to cutting the CO2 from 30 kilometers of car travel.'),
('Choose Green Energy', 'Switch to a green energy plan with your electricity provider.', 'Energy Saving', 'Moderate', 0.5, 1, 'Equivalent to the CO2 savings from 5 days of electricity usage.'),
('Use Smart Power Strips', 'Use smart power strips to prevent standby power loss.', 'Energy Saving', 'Moderate', 0.3, 1, 'Equivalent to saving the CO2 emissions from a laptop running for 5 hours.'),
('Buy Used Items', 'Purchase secondhand goods instead of new ones.', 'Consumption', 'Moderate', 0.5, 1, 'Equivalent to the CO2 savings from producing 1 new item.'),
('Buy Energy-efficient Appliances', 'Invest in energy-efficient appliances for your home.', 'Energy Saving', 'Moderate', 1, 1, 'Equivalent to reducing energy use by 10% in your home.'),
('Wash Full Loads', 'Only run your washing machine or dishwasher when full.', 'Energy Saving', 'Easy', 0.4, 1, 'Equivalent to the CO2 from running half a load of laundry.'),
('Switch Off Appliances', 'Switch off appliances that arent in use.', 'Energy Saving', 'Easy', 0.2, 1, 'Equivalent to the CO2 absorbed by a small plant in a month.'),
('Install Low-flow Showerheads', 'Install low-flow showerheads to conserve water and energy.', 'Water Conservation', 'Moderate', 0.3, 1, 'Equivalent to saving 5 liters of water per shower.'),
('Buy in Bulk', 'Purchase bulk items to reduce packaging waste.', 'Waste Reduction', 'Moderate', 0.4, 1, 'Equivalent to saving CO2 from packaging production.'),
('Plant a Tree', 'Plant a tree to help absorb CO2.', 'Environmental Action', 'Easy', 5, 1, 'Equivalent to planting a tree to absorb CO2 over its lifetime.'),
('Avoid Fast Fashion', 'Avoid buying clothes made by fast fashion brands.', 'Consumption', 'Moderate', 0.5, 1, 'Equivalent to saving CO2 from manufacturing 1 piece of clothing.'),
('Eat Seasonal Produce', 'Eat fruits and vegetables that are in season.', 'Diet', 'Easy', 0.3, 1, 'Equivalent to reducing food miles and emissions.'),
('Use a Clothesline', 'Dry clothes outside using a clothesline instead of a dryer.', 'Energy Saving', 'Easy', 0.3, 1, 'Equivalent to saving energy from 1 hour of dryer use.'),
('Install a Water Filter', 'Install a water filter instead of buying bottled water.', 'Waste Reduction', 'Easy', 0.2, 1, 'Equivalent to saving 10 plastic bottles per month.'),
('Switch to Digital Subscriptions', 'Switch from paper-based subscriptions to digital ones.', 'Waste Reduction', 'Easy', 0.1, 1, 'Equivalent to saving paper from one magazine subscription.'),
('Donate Unused Items', 'Donate items you no longer need instead of throwing them away.', 'Waste Reduction', 'Easy', 0.2, 1, 'Equivalent to preventing the waste of 10 plastic items.'),
('Pick Up Litter', 'Spend 15 minutes picking up litter in your neighborhood.', 'Environment', 'Medium', 0.05, 2, 'Reduce local pollution, protect wildlife, and contribute to a cleaner environment.'),
    ('Install a Rain Barrel', 'Collect rainwater to use for watering plants.', 'Water Conservation', 'Medium', 0.1, 3, 'Conserve water and reduce the energy required for water treatment and transport.'),
    ('Eliminate Single-Use Plastics', 'Go the entire day without using any single-use plastics.', 'Waste Reduction', 'Medium', 0.3, 3, 'Reduce plastic waste and its harmful impact on ecosystems and wildlife.'),
    ('Reduce Water Heating Temperature', 'Lower your water heater''s temperature to save energy.', 'Energy Saving', 'Medium', 0.4, 3, 'Lower energy consumption and reduce your carbon footprint.'),
    ('Donate Unused Electronics', 'Find a charity or recycling program for old gadgets.', 'Waste Reduction', 'Medium', 0.1, 3, 'Reduce e-waste and promote the recycling and reuse of valuable materials.'),
    ('Support a Local Farmers'' Market', 'Buy fresh, local produce instead of store-bought items.', 'Diet', 'Medium', 0.3, 3, 'Support sustainable farming practices and reduce the carbon footprint of food transportation.'),
    ('Plan Errands Efficiently', 'Group errands to minimize driving distances.', 'Transportation', 'Medium', 0.4, 3, 'Reduce car emissions by cutting down on unnecessary trips and fuel usage.'),
    ('Save Rainwater', 'Collect rainwater for household use or plants.', 'Water Conservation', 'Medium', 0.1, 2, 'Conserve fresh water and reduce energy usage related to water processing.'),
    ('Invest in Quality Items', 'Buy durable, high-quality items that last longer.', 'Consumption', 'Medium', 0.2, 3, 'Reduce waste and energy consumption in the production and disposal of low-quality goods.'),
    ('Advocate for Green Policies', 'Write to your local representative about environmental issues.', 'Community', 'Medium', 0.05, 2, 'Encourage government action on climate change and support eco-friendly policies.'),
    ('Refuse Junk Mail', 'Unsubscribe from junk mail to reduce paper waste.', 'Waste Reduction', 'Medium', 0.03, 2, 'Reduce paper waste and save trees, helping to preserve forests.'),
    ('Participate in a Cleanup Event', 'Join a local cleanup event to improve your community.', 'Environment', 'Medium', 0.1, 3, 'Help clean local environments, prevent pollution, and protect wildlife habitats.'),
    ('Switch to Rechargeable Batteries', 'Use rechargeable batteries instead of disposable ones.', 'Waste Reduction', 'Medium', 0.2, 3, 'Reduce battery waste and lessen the environmental harm caused by disposable batteries.'),
    ('Buy Energy-Efficient Appliances', 'Choose energy-efficient options for your next appliance purchase.', 'Energy Saving', 'Medium', 1.0, 5, 'Lower energy consumption and reduce your carbon footprint.'),
    ('Switch to Sustainable Cleaning Products', 'Use eco-friendly cleaning supplies to reduce chemicals.', 'Waste Reduction', 'Medium', 0.1, 2, 'Reduce harmful chemicals in the environment and support safer alternatives.'),
    ('Reduce Use of Paper Towels', 'Switch to cloth towels for cleaning tasks.', 'Waste Reduction', 'Medium', 0.02, 3, 'Reduce paper waste and the carbon footprint associated with paper production.'),
    ('Join a Car-Sharing Service', 'Try a car-sharing service to reduce car ownership dependency.', 'Transportation', 'Medium', 0.5, 3, 'Reduce the number of cars on the road, lowering emissions and traffic congestion.'),
    ('DIY Household Products', 'Make a household product like laundry detergent or soap.', 'Consumption', 'Medium', 0.1, 3, 'Reduce packaging waste and the environmental cost of manufacturing commercial products.'),
    ('Turn Off Appliances', 'Turn off appliances like the dishwasher or dryer before bedtime.', 'Energy Saving', 'Medium', 0.2, 3, 'Save energy and lower your household''s carbon footprint.'),
    ('Start a Mini Garden', 'Grow a small vegetable or herb garden to reduce food miles.', 'Environment', 'Medium', 0.3, 3, 'Reduce the environmental impact of food transportation and promote local food production.'),
    ('Go Car-Free for a Week', 'Avoid using your car for an entire week by biking, walking, or taking public transportation.', 'Transportation', 'Hard', 3.5, 5, 'Significantly reduce CO2 emissions and your reliance on fossil fuels.'),
    ('Install Solar Panels', 'Invest in solar panels for your home or support community solar projects.', 'Energy Saving', 'Hard', 1.7, 5, 'Reduce reliance on non-renewable energy sources and decrease your home''s carbon footprint.'),
    ('Adopt a Zero-Waste Lifestyle for a Week', 'Avoid generating any non-recyclable or non-compostable waste for seven days.', 'Waste Reduction', 'Hard', 1.0, 5, 'Minimize waste production and promote long-term sustainable living habits.'),
    ('Eliminate Meat for a Month', 'Commit to a vegetarian or vegan diet for a month.', 'Diet', 'Hard', 2.5, 5, 'Lower greenhouse gas emissions associated with livestock production.'),
    ('Ditch Your Car', 'Sell your car or stop using it entirely, relying on alternative transportation.', 'Transportation', 'Hard', 3.0, 5, 'Significantly reduce your carbon footprint and reliance on fossil fuels.'),
    ('Transition to a Plant-Based Diet', 'Make a permanent shift to a plant-based diet to reduce your carbon footprint.', 'Diet', 'Hard', 4.0, 5, 'Reduce your impact on the environment by cutting emissions linked to animal agriculture.'),
    ('Build a Composting System', 'Set up a backyard or indoor composting system for long-term use.', 'Waste Reduction', 'Hard', 0.5, 5, 'Reduce landfill waste and produce valuable compost for your garden.'),
    ('Switch to an Electric Vehicle', 'Replace your gas-powered car with an electric or hybrid model.', 'Transportation', 'Hard', 4.0, 5, 'Eliminate tailpipe emissions and reduce dependence on fossil fuels.'),
    ('Downsize Your Living Space', 'Move to a smaller, more energy-efficient home to reduce your resource use.', 'Energy Saving', 'Hard', 2.5, 5, 'Lower energy consumption and reduce your environmental footprint.'),
    ('Plant a Forest', 'Participate in or fund a project to plant a significant number of trees.', 'Environment', 'Hard', 9.0, 5, 'Significantly reduce CO2 levels by increasing global tree coverage.'),
    ('Go Off-Grid for Energy', 'Transition your home to operate off-grid using renewable energy sources.', 'Energy Saving', 'Hard', 3.0, 5, 'Eliminate reliance on the grid and reduce energy consumption and emissions.'),
    ('Quit Fast Fashion Entirely', 'Commit to never buying from fast fashion brands again and choose sustainable clothing options.', 'Consumption', 'Hard', 1.5, 5, 'Reduce textile waste and support ethical, sustainable fashion practices.'),
    ('Buy Nothing for a Month', 'Go an entire month without purchasing anything other than necessities.', 'Consumption', 'Hard', 1.0, 5, 'Reduce consumption and waste, promoting more mindful and sustainable living.'),
    ('Avoid Single-Use Coffee Cups', 'Bring your reusable coffee cup to avoid disposable ones.', 'Waste Reduction', 'Medium', 0.02, 3, 'Reduce waste and cut down on single-use plastic pollution.'),
    ('Walk or Bike for Short Trips', 'For short trips (less than 3 miles), choose to walk or bike instead of driving.', 'Transportation', 'Medium', 0.3, 3, 'Reduce carbon emissions and promote physical health.'),
    ('Eco-Friendly Lawn Care', 'Switch to a more eco-friendly way of maintaining your lawn (e.g., natural fertilizers).', 'Environment', 'Medium', 0.2, 3, 'Reduce chemical runoff and protect local ecosystems.'),
    ('Install Smart Thermostat', 'Install a smart thermostat to optimize your heating and cooling use.', 'Energy Saving', 'Medium', 0.5, 3, 'Lower energy consumption and decrease your carbon footprint.'),
    ('Switch to LED Bulbs', 'Replace your incandescent bulbs with energy-efficient LED bulbs.', 'Energy Saving', 'Medium', 0.1, 3, 'Reduce energy use and lower your electricity bill.'),
    ('Encourage Local Produce in Your Community', 'Advocate for the availability of more locally grown food in your community.', 'Community', 'Medium', 0.2, 3, 'Support local farmers and reduce emissions from transportation.'),
    ('Install Low-Flow Showerheads', 'Replace your showerheads with low-flow versions to save water.', 'Water Conservation', 'Medium', 0.15, 3, 'Lower water and energy usage in your home.'),
    ('Switch to Bamboo Products', 'Replace everyday items (e.g., toothbrushes, towels) with sustainable bamboo alternatives.', 'Waste Reduction', 'Medium', 0.2, 3, 'Reduce plastic waste and promote more sustainable material choices.')
;